#! /usr/bin/env python


import rospy

import actionlib

import behavior_tree_core.msg

from geometry_msgs.msg import Twist




class BTAction(object):
  # create messages that are used to publish feedback/result
  _feedback = behavior_tree_core.msg.BTFeedback()
  _result   = behavior_tree_core.msg.BTResult()

  def __init__(self, name):
    self._action_name = name
    self._as = actionlib.SimpleActionServer(self._action_name, behavior_tree_core.msg.BTAction, execute_cb=self.execute_cb, auto_start = False)
    self._as.start()
    self.pub = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
    self.go_msg = Twist()
    self.go_msg.linear.x = 0
    self.go_msg.linear.y = 0
    self.go_msg.linear.z = 0
    self.go_msg.angular.x = 0
    self.go_msg.angular.y = 0
    self.go_msg.angular.z = 0.2
    
  def execute_cb(self, goal):
    # helper variables
    r = rospy.Rate(25)
    success = True
    

    
    # publish info to the console for the user
    rospy.loginfo('Starting Action')
    
    # start executing the action
    while not rospy.is_shutdown():
      # check that preempt has not been requested by the client
      if self._as.is_preempt_requested():
        stop = Twist()
        stop.linear.x = 0
        stop.linear.y = 0
        stop.linear.z = 0
        stop.angular.x = 0
        stop.angular.y = 0
        stop.angular.z = 0
        self.pub.publish(stop)
        rospy.loginfo('Action Halted')
        self._as.set_preempted()
        success = False
        break

      rospy.loginfo('Go stright ... ... ')
      self.pub.publish(self.go_msg)
      # this step is not necessary, the sequence is computed at 1 Hz for demonstration purposes
      r.sleep()
      
    if success:
      self.set_status('SUCCESS')

    

  def set_status(self,status):
      if status == 'SUCCESS':
        self._feedback.status = 1
        self._result.status = self._feedback.status
        rospy.loginfo('Action %s: Succeeded' % self._action_name)
        self._as.set_succeeded(self._result)
      elif status == 'FAILURE':
        self._feedback.status = 2
        self._result.status = self._feedback.status
        rospy.loginfo('Action %s: Failed' % self._action_name)
        self._as.set_succeeded(self._result)
      else:
        rospy.logerr('Action %s: has a wrong return status' % self._action_name)



if __name__ == '__main__':
  rospy.init_node('rotate')
  BTAction(rospy.get_name())
  rospy.spin()
